# Generated by Django 5.0.1 on 2024-01-21 11:58

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chameleon_project_ticket", "0002_alter_chameleonticket_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChameleonCommentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.BigIntegerField()),
                ("timestamp", models.DateTimeField()),
                (
                    "action",
                    models.CharField(help_text="History action", max_length=255),
                ),
                ("field", models.TextField(null=True)),
                ("value_from", models.TextField(blank=True, null=True)),
                ("value_to", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChameleonComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Comment description", null=True),
                ),
                (
                    "description_markup",
                    models.CharField(
                        choices=[
                            ("PLAIN", "Plain"),
                            ("MARKDOWN", "Markdown"),
                            ("ASCIIDOC", "Asciidoc"),
                        ],
                        default="PLAIN",
                        help_text="Comment description markup language",
                        max_length=255,
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(help_text="When comment has been created"),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chameleon_project_ticket.chameleonticket",
                    ),
                ),
            ],
            options={
                "ordering": ["creation_time"],
            },
        ),
    ]
