# Generated by Django 5.0 on 2023-12-24 23:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("chameleon_project_project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChameleonProjectHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.BigIntegerField()),
                ("timestamp", models.DateTimeField()),
                (
                    "action",
                    models.CharField(help_text="History action", max_length=255),
                ),
                ("field", models.TextField(null=True)),
                ("value_from", models.TextField(blank=True, null=True)),
                ("value_to", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
