# Generated by Django 5.0 on 2024-01-15 17:15

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("chameleon_project_project", "0002_chameleonprojecthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="chameleonproject",
            name="creation_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 1, 0, 0, 0, 0, tzinfo=datetime.UTC),
                help_text="When project has been created",
            ),
        ),
    ]
