# Generated by Django 5.0 on 2024-01-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chameleon_project_project", "0003_chameleonproject_creation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chameleonproject",
            name="creation_time",
            field=models.DateTimeField(help_text="When project has been created"),
        ),
    ]
