# Generated by Django 5.0.1 on 2024-01-21 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chameleon_project_project", "0004_alter_chameleonproject_creation_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chameleonproject",
            options={"ordering": ["creation_time"]},
        ),
    ]
