# Generated by Django 5.0.1 on 2024-02-10 09:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("chameleon_project_project", "0005_alter_chameleonproject_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="chameleonproject",
            name="name",
            field=models.CharField(
                db_default=models.Value("abc"), help_text="Project name", max_length=50
            ),
        ),
    ]
