# Generated by Django 5.0.1 on 2024-02-10 09:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("chameleon_project_project", "0006_chameleonproject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chameleonproject",
            name="name",
            field=models.CharField(help_text="Project name", max_length=50),
        ),
    ]
