# Generated by Django 5.0.3 on 2024-03-04 19:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("chameleon_project_project", "0007_alter_chameleonproject_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chameleonproject",
            old_name="title",
            new_name="summary",
        ),
        migrations.AlterField(
            model_name="chameleonproject",
            name="summary",
            field=models.CharField(help_text="Project summary", max_length=200),
        ),
    ]
