# Generated by Django 5.0.1 on 2024-01-21 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chameleon_project_ticket", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chameleonticket",
            options={"ordering": ["creation_time"]},
        ),
    ]
