# Generated by Django 4.2.7 on 2023-11-13 18:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChameleonProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Project title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Project description"),
                ),
                (
                    "description_markup",
                    models.CharField(
                        choices=[
                            ("PLAIN", "Plain text"),
                            ("MARKDOWN", "Markdown"),
                            ("ASCIIDOC", "AsciiDoc"),
                        ],
                        default="PLAIN",
                        help_text="Project description markup language",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
