---
openapi: 3.0.0
info:
  title: Ticket Object API
  version: 0.0.1
paths:
  /api/ticket/{ticketId}:
    get:
      description: Retrieve given ticket
      parameters:
      - name: ticketId
        in: path
        description: public ID of ticket to return info
        required: true
        schema:
          $ref: ../schema_common.yml#/$defs/GenericPublicId
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: ../schema_ticket.yml#/$defs/ChameleonTicket
        '400':
          description: Invalid input
        '404':
          description: Object not found
    post:
      description: ''
      parameters:
      - name: ticketId
        in: path
        description: public ID of ticket that needs to be updated
        required: true
        schema:
          $ref: ../schema_common.yml#/$defs/GenericPublicId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../schema_ticket.yml#/$defs/ChameleonTicketUpdate
      responses:
        '204':
          description: Successful operation
        '400':
          description: Invalid input
        '404':
          description: Ticket not found
  /api/ticket/{ticketId}/history:
    get:
      description: Retrieve change history for ticket
      parameters:
      - name: ticketId
        in: path
        description: public ID of ticket to return history for
        required: true
        schema:
          $ref: ../schema_common.yml#/$defs/GenericPublicId
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../schema_common.yml#/$defs/ObjectHistory
        '400':
          description: Invalid input
        '404':
          description: Object not found
  /api/project/{projectId}/ticket:
    get:
      description: List available projects
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../schema_comment.yml#/$defs/ChameleonComment
    post:
      description: Create new project
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../schema_comment.yml#/$defs/ChameleonCommentCreate
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: ../schema_comment.yml#/$defs/ChameleonComment
